### PR TITLE
Update driver window resize methods

### LINKED ISSUE #24: chrome doesn't resize
> irb
    > require 'webdriver-user-agent'
    > driver = Webdriver::UserAgent.driver(browser: :chrome) 

doesn't open an iphone size window.

### PR DESCRIPTION
**Pull request by samnissen**
- Fixes #24 
- Update to testing per comments on #2

### CODE REVIEW

**Comment by samnissen** [comment]
Pinging @cheezy to get this merged in.

**Comment by samnissen** [comment]
@cheezy @alisterscott Pinging again.

**Comment by cheezy** [comment]
Sam, got your ping. I'm camping with my sons this week with limited connectivity. How can I help you?

**Comment by samnissen** [comment]
@cheezy No particular reason to rush this this week -- please go back to camping and let's talk another time! 

I'm pinging on these PRs as I believe they are ready to be merged. And if they aren't I'd be happy to change them as necessary.

**Comment by cheezy** [comment]
Sam,

I come off the trail on Saturday and would be happy to look at these over the weekend.

-Cheezy

**Comment by samnissen** [comment]
Cheers!

**Pull request merged**
